services:
  main-db:
    image: 'postgres'
    container_name: 'booking-system-main'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=booking-system-main
    ports:
      - "2345:5432"

  test-db:
    image: 'postgres'
    container_name: 'booking-system-test'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=booking-system-test
    ports:
      - "2346:5432"